language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcairo2-dev libpango1.0-dev libtokyocabinet-dev imagemagick jp2a
script: 
  - autoreconf -i 
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - sudo duc index -x /
  - sudo duc ls /usr
  - sudo duc graph /
  - identify duc.png
  - convert duc.png duc.jpg
  - jp2a duc.jpg
  - ls -l /dev/stdin /dev/stdout /dev/stderr
  - ls -l /proc/self/fd/0 /proc/self/fd/1 /proc/self/fd/2
  
